name: ios build scripts

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to use for release (e.g., v6.0.2)'
        required: true
        default: 'v6.0.2'
      xcode:
        description: 'Xcode version to build with'
        required: true
        default: '16.1'

jobs:
  build-main-on-macos-sonoma:
    name: ios main on sonoma
    runs-on: macos-14-xlarge
    env:
      XCODE_VERSION: ${{ github.event.inputs.xcode }}
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: prerequisites
        run: brew install autoconf automake libtool pkg-config curl git cmake nasm
      - name: set up xcode
        run: |
          XCODE_VERSION="${XCODE_VERSION:-16.1}"
          ls -l /Applications/Xcode*.app
          echo "export DEVELOPER_DIR=/Applications/Xcode_${XCODE_VERSION}.app/Contents/Developer" > ~/.xcode.for.ffmpeg.kit.sh
      - name: run the build script
        run: ./ios.sh --xcframework --enable-ios-audiotoolbox --enable-ios-avfoundation --enable-ios-bzip2 --enable-ios-libiconv --enable-ios-videotoolbox --enable-ios-zlib
      - name: print build logs
        if: ${{ always() }}
        run: cat build.log
      - name: print ffbuild logs
        if: ${{ failure() }}
        run: '[[ -f ./src/ffmpeg/ffbuild/config.log ]] && tail -50 ./src/ffmpeg/ffbuild/config.log'
      - name: Prepare dist directory
        if: ${{ success() }}
        run: |
          mkdir -p dist
          cp -R prebuilt/bundle-apple-xcframework-ios/*.xcframework dist/
          cd dist
          zip -r ffmpegkit-ios.zip *.xcframework
      - name: Create Release
        if: ${{ success() && github.event.inputs.tag != '' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          files: |
            dist/ffmpegkit-ios.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
